name: github pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: latest
        cache: npm

    - run: npm ci
    - run: npm run build
    - run: touch dist/.nojekyll

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: podcast.allegro.tech
    
    - uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_TOKEN }}
        repository: allegro/allegro.tech
        event-type: blog-update
